server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: service-car
          uri: lb://service-car
          predicates:
            - Path=/car/**
        - id: service-bike
          uri: lb://service-bike
          predicates:
            - Path=/bike/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/auth/realms/mcsv-app-shop/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/auth/realms/mcsv-app-shop/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8180/auth/realms/mcsv-app-shop/protocol/openid-connect/token
        registration:
          spring-mcsv-new:
            provider: keycloak
            client-id: spring-mcsv-new
            client-secret: l1wjyO9kwzMalJjCgsKVN7C1cl92iAWM
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/spring-mcsv-new"
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
    